Support for unblocked user tags
GeneralNotability/spihelper pull request #10
Opened 2020-12-11 00:38 UTC by Dreamy-Jazz

Add support for users who are not blocked, but tagged
Fixes 9

2020-12-11 10:26 UTC, Dreamy-Jazz commented
That should work. notBlocked takes the opposite of whether someone is blocked. Therefore, I've changed the parameter name to isNotBlocked and swapped yes / no to reflect this.

2021-01-05 19:24 UTC, GeneralNotability requested changes

2021-01-05 21:13 UTC, Dreamy-Jazz commented on spihelper.js
> +| notblocked = ${isBlocked}
Done

2021-01-05 21:14 UTC, Dreamy-Jazz commented on spihelper.js
> +				const isNotBlocked = await spiHelper_getUserBlockReason(tagEntry.username) ? 'yes' : 'no';
Fixed. The double negatives with the variable name confused me.

2021-01-05 21:18 UTC, Dreamy-Jazz commented
I've made those two changes as noted by you.

2021-01-06 02:17 UTC, GeneralNotability approved these changes
Looks good to me! Thanks for the rework.

2021-01-06 02:17 UTC, merged